name: Build and Test
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.100-rc.2.25502.107"

      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Build
        run: dotnet build --no-restore --configuration Release ./src

      - name: Tests
        run: dotnet test --no-build --configuration Release ./src